image: python:3.10-slim

variables:
  SITE_URL: https://sosiristseng.gitlab.io/template-mkdocs-material/
  REPO_URL: https://gitlab.com/sosiristseng/template-mkdocs-material/
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  - key:
      files:
        - requirements.txt
    paths:
      - .cache/pip
      - venv/

before_script:
  - python -m venv venv/
  - source venv/bin/activate
  - python -m pip install -r requirements.txt
  - mkdocs build --site-dir public

build:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
  - echo "Build completed."

pages:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
  - apt-get update -qq && apt-get install gzip brotli -y
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
