image: python:3.9-slim

stages:
  - test
  - deploy

variables:
  SITE_URL: https://sosiristseng.gitlab.io/template-mkdocs-material/
  REPO_URL: https://gitlab.com/sosiristseng/template-mkdocs-material/
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  - key:
      files:
        - requirements.txt
    paths:
      - .cache/pip

before_script:
  - python -m pip install -r requirements.txt
  - mkdocs build --site-dir public

test:
  stage: test
  except:
  - main
  script:
  - echo "Test completed."

pages:
  stage: deploy
  only:
  - main
  script:
  - apt-get update -qq && apt-get install gzip brotli -y
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
