site_name: My MkDocs Template
site_url: https://sosiristseng.github.io/template-mkdocs-material/
site_author: Wen-Wei Tseng

# Repository
repo_url: https://github.com/sosiristseng/template-mkdocs-material
# Leave blank to disable the edit button,
edit_uri: ""

copyright: Copyright &copy; 2016 - 2021 Wen-Wei Tseng

# MkDocs plugins
plugins:
  - search

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share


# Social buttons at bottom
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/user
    - icon: fontawesome/brands/github
      link: https://github.com/user
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0000-0000-0000
    - icon: fontawesome/solid/paper-plane
      link: mailto:a@b.com
    
# Extensions: 
# https://python-markdown.github.io/extensions/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.caret
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  # - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md