name: Build pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      # - uses: actions/cache@v3
      #   with:
      #     key: ${{ github.ref }}
      #     path: .cache
      - name: Build website for PRs
        if: github.ref != 'refs/heads/main'
        run: mkdocs build
      - name: Deploy for main
        if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
